import React from 'react';
import BoltIcon from '@mui/icons-material/Bolt';
import * as Read from './read';
import * as Exec from './exec';

const DefaultBoltIcon = React.createElement(BoltIcon);

/**
 * Returns the list of read commands.
 * @param {Object} dependencies - Dependencies for the commands.
 * @param {Function} dependencies.getContext - Function to retrieve context.
 * @param {Object} dependencies.icons - Object containing icon components.
 * @param {Object} dependencies.icons.Bolt - Bolt icon component.
 * @returns {Array} List of read command definitions.
 */
export const getReadCommands = ({ getContext, icons }) => [
  {
    id: 'command_center.read.scope.get',
    label: '/get-current-scope',
    description: 'Get the current scope (route, module, focus)',
    skills: {},
    action: () => Read.getCurrentScope(getContext('page-context')),
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.read.insights.list',
    label: '/list-insights',
    description: 'List available InsightSources by scope',
    skills: {},
    action: Read.listInsights,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.read.insights.describe',
    label: '/describe-insight',
    description: 'View metadata + schema of an InsightSource',
    skills: {},
    action: Read.describeInsight,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.read.insights.snapshot',
    label: '/snapshot-insight',
    description: 'Pull snapshot (respects TTL/cache)',
    skills: {},
    action: Read.snapshotInsight,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.read.context.pack',
    label: '/context-pack',
    description: 'Pull multiple insights (Top-N or by IDs)',
    skills: {},
    action: Read.contextPack,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.read.page.outline',
    label: '/page-outline',
    description: "What's on the page using insights (non-DOM)",
    skills: {},
    action: () => Read.getPageOutline(getContext('page-context')),
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.read.selection.get',
    label: '/get-selection',
    description: 'Get opt-in selection (text/IDs)',
    skills: {},
    action: Read.getSelection,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.read.focus.get',
    label: '/get-focus',
    description: 'Get active focus (entity/active panel)',
    skills: {},
    action: Read.getFocus,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.read.ui.surfaces.list',
    label: '/list-surfaces',
    description: 'List published surfaces (modals, grids, forms)',
    skills: {},
    action: Read.listSurfaces,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.read.ui.targets.list',
    label: '/list-targets',
    description: 'List targets of a surface',
    skills: {},
    action: Read.listTargets,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.observe.ui',
    label: '/observe-ui',
    description: 'Discover candidate actions from instruction',
    skills: {},
    action: Read.observeUi,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.extract.from_insight',
    label: '/extract-from-insight',
    description: 'Extract structured data from an InsightSource',
    skills: {},
    action: Read.extractFromInsight,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.extract.from_targets',
    label: '/extract-from-targets',
    description: 'Extract data from published targets',
    skills: {},
    action: Read.extractFromTargets,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.read.debug.router_log',
    label: '/debug-router-log',
    description: 'View last N router decisions',
    skills: {},
    action: Read.debugRouterLog,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.read.debug.execution_log',
    label: '/debug-exec-log',
    description: 'View last N executions + receipts',
    skills: {},
    action: Read.debugExecutionLog,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.read.tasks.inbox',
    label: '/tasks-inbox',
    description: 'List HITL Tasks assigned to user',
    skills: {},
    action: Read.listTasksInbox,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.read.tasks.detail',
    label: '/task-detail',
    description: 'View detail + required inputs schema',
    skills: {},
    action: Read.getTaskDetail,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.read.capabilities',
    label: '/capabilities',
    description: 'See what reading/execution is enabled on host',
    skills: {},
    action: Read.getCapabilities,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
];

/**
 * Returns the list of exec commands.
 * @param {Object} dependencies - Dependencies for the commands.
 * @param {Function} dependencies.navigate - Function to navigate.
 * @param {string} dependencies.routeDescription - Description of routes.
 * @param {Object} dependencies.icons - Object containing icon components.
 * @param {Object} dependencies.icons.Bolt - Bolt icon component.
 * @returns {Array} List of exec command definitions.
 */
export const getExecCommands = ({ navigate, routeMap, icons }) => [
  {
    id: 'command_center.exec.ui.act',
    label: '/act-ui',
    description: 'Execute deterministic action on a target',
    skills: {},
    action: Exec.actUi,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.exec.ui.act_batch',
    label: '/act-batch-ui',
    description: 'Execute sequence of UI actions',
    skills: {},
    action: Exec.actBatchUi,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.exec.ui.open_surface',
    label: '/open-surface',
    description: 'Open a published surface',
    skills: {},
    action: Exec.openSurface,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.exec.ui.close_surface',
    label: '/close-surface',
    description: 'Close surface',
    skills: {},
    action: Exec.closeSurface,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.exec.ui.set_fields',
    label: '/set-fields',
    description: 'Set multiple fields in a FormSurface',
    skills: {},
    action: Exec.setFields,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.exec.ui.submit_form',
    label: '/submit-form',
    description: 'Submit published form',
    skills: {},
    action: Exec.submitForm,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.exec.ui.apply_filter',
    label: '/apply-filter',
    description: 'Apply filters on Grid/List surface',
    skills: {},
    action: Exec.applyFilter,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.exec.ui.select_rows',
    label: '/select-rows',
    description: 'Select rows/items',
    skills: {},
    action: Exec.selectRows,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.exec.command.invoke',
    label: '/invoke-command',
    description: 'Execute semantic command published by feature',
    skills: {},
    action: Exec.invokeCommand,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.exec.app.open',
    label: '/open-app',
    description: 'Open HITL App and return outputs',
    skills: {},
    action: Exec.openApp,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.exec.navigate',
    label: '/navigate',
    description: 'Navigate to a specific route within the application based on the known routes skill.',
    app: 'Command Center',
    schema: {
      type: 'object',
      properties: {
        route: {
          type: 'string',
          description: 'Target absolute path (e.g. /admin/projects)',
        },
      },
      required: ['route'],
    },
    skills: {
      routes: routeMap,
    },
    action: (args) => Exec.navigate(args, navigate),
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.exec.clipboard.copy',
    label: '/copy',
    description: 'Copy an artifact to clipboard',
    skills: {},
    action: Exec.copyToClipboard,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.exec.tasks.claim',
    label: '/claim-task',
    description: 'Take ownership of a HITL Task',
    skills: {},
    action: Exec.claimTask,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.exec.tasks.complete',
    label: '/complete-task',
    description: 'Complete task with validated outputs',
    skills: {},
    action: Exec.completeTask,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.exec.tasks.comment',
    label: '/comment-task',
    description: 'Add comment to task',
    skills: {},
    action: Exec.commentTask,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
  {
    id: 'command_center.exec.undo',
    label: '/undo',
    description: 'Attempt to revert an action',
    skills: {},
    action: Exec.undo,
    app: 'Command Center',
    icon: icons?.Bolt || DefaultBoltIcon,
  },
];
